# Generated by Django 2.0.3 on 2019-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lodgeunitinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dayprice', models.IntegerField()),
                ('estate', models.CharField(choices=[('valid', 'valid'), ('deleted', 'deleted')], default='valid', max_length=10)),
                ('minday', models.IntegerField()),
                ('maxday', models.IntegerField()),
                ('tel', models.CharField(max_length=11)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remarks', models.CharField(max_length=500)),
                ('address_id', models.CharField(max_length=50)),
                ('image_md5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalprice', models.IntegerField(default=0)),
                ('estate', models.CharField(choices=[('valid', 'valid'), ('deleted', 'deleted')], default='valid', max_length=10)),
                ('guestnum', models.IntegerField(default=1)),
                ('checkinday', models.CharField(max_length=20)),
                ('checkoutday', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('remarks', models.CharField(max_length=500)),
                ('luid', models.IntegerField()),
            ],
        ),
    ]
