# Generated by Django 2.0.3 on 2019-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='estate',
            field=models.CharField(choices=[('deleted', 'deleted'), ('valid', 'valid')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('deleted', 'deleted'), ('valid', 'valid')], default='valid', max_length=10),
        ),
    ]
