# Generated by Django 2.0.3 on 2019-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20190502_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('deleted', 'deleted')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('deleted', 'deleted')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
