# Generated by Django 2.0.3 on 2019-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20190502_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='others_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalprice', models.IntegerField(default=0)),
                ('estate', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=500)),
                ('order_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='estate',
            field=models.CharField(choices=[('deleted', 'deleted'), ('valid', 'valid')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('deleted', 'deleted'), ('valid', 'valid')], default='valid', max_length=10),
        ),
    ]
