# Generated by Django 2.0.3 on 2019-05-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20190504_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('cancel', 'cancel'), ('done', 'done'), ('valid', 'valid')], default='valid', max_length=10),
        ),
    ]
