# Generated by Django 2.2.1 on 2019-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20190507_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('done', 'done'), ('cancel', 'cancel'), ('valid', 'valid')], default='valid', max_length=10),
        ),
    ]
