# Generated by Django 2.0.3 on 2019-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20190509_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='estate',
            field=models.CharField(choices=[('deleted', 'deleted'), ('valid', 'valid')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('cancel', 'cancel'), ('done', 'done')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='others_order',
            name='estate',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
