# Generated by Django 2.0.3 on 2019-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20191218_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('cancel', 'cancel'), ('done', 'done'), ('valid', 'valid')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='others_order',
            name='estate',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=10),
        ),
    ]
