# Generated by Django 2.0.3 on 2020-04-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20191223_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='checkinday',
            new_name='checkInDate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='checkoutday',
            new_name='checkOutDate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guestnum',
            new_name='guestNum',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='luid',
            new_name='luId',
        ),
        migrations.AlterField(
            model_name='lodgeunitinfo',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('deleted', 'deleted')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('done', 'done'), ('cancel', 'cancel')], default='valid', max_length=10),
        ),
    ]
